### ISSUE TITLE
[Feature] Add support for a headered text block control

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE.NET#1]
The HeaderedTextBlock UWP control has been ported from the WinUX library with an implementation available for Android. 

The idea for the control is to have a header component for read-only text, i.e. a TextBlock in UWP or a TextView in Android. This is useful when building form based scenarios where content from a model is usually shown with it's property (header) and the value (text).

The remaining work for this item is for an iOS and Xamarin Forms implementation.

**Comment by jamesmcroft** [comment]
Started taking a look at building custom controls for iOS and fleshing out the content for the HeaderedTextBlock on the [iOS Custom Control branch](https://github.com/MADE-Apps/MADE-App-Components/tree/ios-customcontrols)

**Comment by jamesmcroft** [comment]
The custom control logic is now merged into the master branch. The implementation for the HeaderedTextBlock can be completed.

**Comment by jamesmcroft** [comment]
The iOS component now exists. Just requires a component for Xamarin Forms.

**Comment by tom-made** [comment]
Thanks for the help with this @jamesmcroft 

This issue is now complete.

**Comment by jamesmcroft** [comment]
Thanks @tom-made! I think there are some improvements that could be made to the Forms component, in particular, possibly making it a control using custom renderers taking advantage of the current MADE platform specific components. For now though, what I built works as intended.

**Comment by tom-made** [comment]
I know based on #42 that there are still issues with the iOS component. I will leave this in but update the tags
