### ISSUE TITLE
Validator feedback message control contains empty line in the end

### ISSUE THREAD

**Issue by Dieveral** [MADE-Apps/MADE.NET#111]
MADE.NET.Controls.Validator 1.0.0-preview2 (Nuget)

UAP v10.0.17763

![empty_line_bug](https://user-images.githubusercontent.com/50696412/109486854-77e24c80-7a94-11eb-9bd3-5e1d26c6f77f.jpg)

ValidatorFeedbackMessage control inside InputValidator control has Text that ends with "\r\n".
Strings concatenation with StringBuilder.AppendLine() leaves "\r\n" in the end of result string.

![debug](https://user-images.githubusercontent.com/50696412/109487390-343c1280-7a95-11eb-8218-5b992f14741f.jpg)

**Steps to reproduce**
1. Add InputValidator control on page;
2. Add TextBlock inside InputValidator;
3. Add binding to ValidatorCollection (for example: { new RequiredValidator(), new EmailValidator() });
4. If validation feedback message is shown we see empty space (1 empty line) after validation message.

**Expected behavior**
No empty line after validation feedback message.
![desired](https://user-images.githubusercontent.com/50696412/109486425-ea066180-7a93-11eb-8844-36e9061eb0f9.jpg)

**Comment by jamesmcroft** [comment]
Thanks for the contribution @Dieveral 🙌
