### ISSUE TITLE
[Feature] Add support for an easy to use media playback control

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE.NET#13]
This control needs an implementation for Android, iOS, Forms, and UWP with similar functionality to that of the UWP's media player.

As basic functions, it should provide the ability to play and pause, stop, skip to next, back to previous and should support both audio and video formats, being responsive to the type playing.

**Comment by peterfoot** [comment]
I created a UWP style MediaElement for Xamarin Forms here - https://github.com/inthehand/InTheHand.Forms
It's fairly mature and has been used in a variety of real-world apps. Happy to take enhancements or suggestions!

**Comment by tom-made** [comment]
Going to re-open this. Probably requires #32 to be completed first.
