### ISSUE TITLE
[Feature] Add content carousel control

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE.NET#15]
This control needs an implementation for Android, iOS, Forms, and UWP with functionality that is similar to a standard web carousel view which allows a user to swipe through carousel items. 

The control should support any type of content, for example, a user could create a carousel item that was both an image and text. 

The implementation should follow the pattern of a common interfaced component with an implementation per platform using the MADE base Control type.

**Comment by tom-made** [comment]
Carousel controls are great and this would be a welcomed addition. Will need to discuss transitions and improvements to make this a great feature control. Requires #32 to be completed first.
