### ISSUE TITLE
[Feature] Add control for step incrementing a numeric value

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE.NET#16]
This control needs an implementation for Android, iOS, Forms, and UWP with functionality that is similar to the iOS stepper control and the implementation that exists for UWP in the WinUX app toolkit.

The control should allow a user to easily increment or decrement a value.

The implementation should follow the pattern of a common interfaced component with an implementation per platform using the MADE base Control type.

**Comment by tom-made** [comment]
Again, happy to see this added. Will require #32 to be completed first.
