### ISSUE TITLE
[Feature] Add support for a drawing control

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE.NET#2]
A port and implementation required from the WinUX DrawingCanvas control which supports the ability to draw and save ink.

The implementation should follow the pattern of a common interfaced component with an implementation per platform using the MADE base Control type.

**Comment by jamesmcroft** [comment]
Started work on this 😄

**Comment by tom-made** [comment]
Sorry, going to re-open this. Will require #32 to be completed first.
