### ISSUE TITLE
[Feature] Implement common page/navigation model

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE.NET#29]
**Is your feature request related to a problem? Please describe.**

When developing applications, the main core component is how the pages hang together. 

**Describe the solution you'd like**

I propose that we develop a component for implementing common page to page navigation across Windows, Android and iOS. The idea would potentially take a leaf out of Windows' book by implementing a common Frame component for handling navigation.

**Describe alternatives you've considered**

Another implementation would be just to create a navigation service and allow developers to pick their method of execution. The only difficulty with this is that MADE is designed to make development easier and this library should be handling all of that for the developer.

**Comment by tom-made** [comment]
Happy for this to be the focus of the reshuffle branch. Will start splitting out other components.

**Comment by jamesmcroft** [comment]
With the PR, I've sorted out the builds so that it should start pumping out the packages to the internal package source. I've also wired in SonarQube analysis with SonarCloud for code checking.

**Comment by tom-made** [comment]
Going to re-open this. We have implementations for Android and Windows but not iOS!
