### ISSUE TITLE
[Feature] Add support for an expanding content control

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE.NET#4]
A port and implementation required from the WinUX Expander control which supports the ability to expand and collapse a content section like an accordion!

The implementation should follow the pattern of a common interfaced component with an implementation per platform using the MADE base Control type.

**Comment by tom-made** [comment]
Although mostly similar, it may be a good idea to build something close to the Expander control from the System.Windows.Controls namespace in WPF (https://msdn.microsoft.com/en-us/library/system.windows.controls.expander(v=vs.110).aspx)

**Comment by jamesmcroft** [comment]
@tom-made more than happy for it to follow a similar structure. When initially built, it was based loosely on the WPF expander control. The only difference is that the one I created only worked expanding down.

**Comment by tom-made** [comment]
Again, re-opening this. Can see it's usefulness in the project. Also, #32 will need to be completed first.
