### ISSUE TITLE
[Feature] Add support for validation on text box controls

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE.NET#6]
A port and implementation required from the WinUX ValidatingTextBox control which supports the ability to write and use custom validation rules to validate the input of a text box control. 

The implementation should follow the pattern of a common interfaced component with an implementation per platform using the MADE base Control type.

**Comment by jamesmcroft** [comment]
Picking the first part of this up with a port from WinUX for the UWP component.

**Comment by tom-made** [comment]
I will re-open this but we need to take a look at better ways of integrating this. #32 will need to be completed first.
